[versions]
kotlin = "1.5.0"
slf4j = "1.7.30"
logback = "1.2.3"
junit = "5.6.2"
mockk = "1.10.0"
detekt = "1.17.0-RC3"

[libraries]
# Logging
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }

# Linter
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

# Testing
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[bundles]
logging = ["slf4j", "logback-classic", "logback-core"]
test = ["junit-api", "mockk", "junit-engine"]